version: '3.7'

services:
  webserver:
    image: nginx:alpine
    volumes:
      - magento-data:/var/www
      - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - VIRTUAL_HOST=www.openmage.test
      - VIRTUAL_PORT=80
    env_file:
      - magento.env
    links:
      - db
      - php-fpm

  php-fpm:
    build:
      context: ../../container/php/
    volumes:
      - magento-data:/var/www
#      - ../../var/application/:/var/www:delegated
#      - ../../var/cache/composer/:/root/.composer/:delegated
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
    depends_on:
      - db
    links:
      - db

  db:
    image: mysql:5.7
#    volumes:
#      - db-data:/var/lib/mysql/data
    environment:
      - VIRTUAL_HOST=mysql.openmage.test
    env_file:
      - magento.env

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - VIRTUAL_HOST=phpmyadmin.openmage.test
      - VIRTUAL_PORT=80
    links:
      - db

  sftp:
    image: atmoz/sftp:alpine
    volumes:
      - magento-data:/home/sftp/var/www
    #  - type: volume
    #  - source: ./ssh/ssh_host_rsa_key
    #  - target: /etc/ssh/ssh_host_rsa_key
    #  - ./ssh/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key:delegated
    #  - ./ssh/ssh_host_rsa_key.pub:/etc/ssh/ssh_host_rsa_key.pub:delegated
    depends_on:
      - php-fpm
    ports:
      - "22:22"
    #environment:
    #  - VIRTUAL_HOST=www.openmage.test
    #  - VIRTUAL_PORT=2222
    #command: www-data:$1$FzEALFS2$yUdwhXqgO1E.lUOXyheNH/:e:1001 # your-password
    command: sftp:your-password:1000 # your-password

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
volumes:
  db-data:
  magento-data:
